// <auto-generated />
using System;
using ERep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERep.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ERep.Models.CSR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Carteles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDiagnostico")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSintomas")
                        .HasColumnType("TEXT");

                    b.Property<int>("EreumaticaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Facebook")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Instagram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Internet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Periodico")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Platicas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Radio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RedesSociales")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Television")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TikTok")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEmbarazoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Twitter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WhatsApp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("actividad_despues_parto_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("actividad_despues_parto_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("actividad_despues_parto_3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("anticon_contraponeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_contraponeotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("anticon_dondeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_dondeotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("anticon_edadprimeraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("anticon_histusoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("anticon_operoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_operootro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("anticon_primerapro1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro12")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro13")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro14")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro15")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro16")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_primerapro9")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_primeraprototro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("anticon_primerarazonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_primerarazonotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("anticon_razonnousaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_razonnousaotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("anticon_razonreceta_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_12")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anticon_razonreceta_9")
                        .HasColumnType("INTEGER");

                    b.Property<string>("anticon_razonrecetaotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("anticon_usoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cesarea_decidioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cesarea_ener_motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cesarea_motivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cesarea_motivootro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("embarazada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("embarazadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hijosahoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hijosalgunavezId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hijosesperaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hijosesperanum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hijosnacvivosfall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hijosnodeseananoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hijosnodeseananootro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("hijosnodeseanuncaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hijosnodeseanuncaotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("hijosnopuedeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hijosnopuedeotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("hijosnorazonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hijosnorazonotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("lechematerna_dejadarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lechematerna_dejadarotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("lechematerna_dias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("lechematerna_dio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lechematerna_duracionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lechematerna_horas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lechematerna_nodioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lechematerna_nodiootro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("medicamento_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_12")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_13")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_14")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_15")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_16")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_17")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_9")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("medicamento_otros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("medicamento_otros_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("metodos_conoce_a")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_b")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_c")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_d")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_e")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_f")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_g")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_h")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_i")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_j")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_l")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_m")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_n")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_conoce_nn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("metodos_conoce_o")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("metodos_funciona_a")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_b")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_c")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_d")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_e")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_f")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_g")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_h")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_i")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_j")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_l")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_m")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_n")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_funciona_nn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("metodos_funciona_o")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("metodos_utiliza_a")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_b")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_c")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_d")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_e")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_f")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_g")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_h")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_i")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_j")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_k")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_l")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_m")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_n")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("metodos_utiliza_nn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("metodos_utiliza_o")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("numabortos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numembarazos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numhijosdesea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("otraEreumatica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("otra_red")
                        .HasColumnType("INTEGER");

                    b.Property<string>("otra_red_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("otro_medio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("otro_medio_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("parto_tipoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_12")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_13")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_14")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_15")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_16")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_17")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_18")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_19")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_20")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_21")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_22")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_23")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_24")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_25")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_26")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_27")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_28")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_29")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_30")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_9")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("partomedicamento_otros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("partomedicamento_otros_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("pnumhijosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("reuma_confianzaplanificarfamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("reuma_planificarfamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("reuma_riesembarazoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("reuma_riesgomedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rmashijosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rmenoshijosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimaregla_anos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimaregla_dias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ultimaregla_menopausia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimaregla_meses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ultimaregla_nodecir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ultimaregla_nohamestruado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ultimaregla_norecuerdo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimaregla_semanas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimarelaciones_anos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimarelaciones_dias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimarelaciones_meses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ultimarelaciones_nodecir")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ultimarelaciones_semanas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("vianac_decidioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("CSRs");
                });

            modelBuilder.Entity("ERep.Models.PartosInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlimentoBebesmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniosTotales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtendidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CSRId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CesareaMotivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CesareaOtros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarPechoAntes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DarPechoAntesRazonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefuncionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DejoDarleLechePechoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DejoDarleLechePechoOtros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DespuesParto1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DespuesParto2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DespuesParto3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DespuesParto4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DespuesParto5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DespuesParto6")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Dia")
                        .HasColumnType("REAL");

                    b.Property<int>("DiasDesp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasTotales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EligioTipoAlimId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GestacionTipoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HijoVivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorasDesp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorasTotales")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InfoLactancia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mes")
                        .HasColumnType("REAL");

                    b.Property<int>("MesesTotales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutosDesp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutosTotales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NuncaLechePechoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NuncaLechePechoOtros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartoCesareaAbortoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PensabaAlimentarloId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<bool>("Reactivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemanasGestacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SitioInfoLactanciaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Talla")
                        .HasColumnType("REAL");

                    b.Property<double>("Year")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CSRId");

                    b.ToTable("PartosInfos");
                });

            modelBuilder.Entity("ERep.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BornDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPartner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ECU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iniciales")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Residencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Residencialugar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("aceptoconocimieto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("escolaridad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("escolaridadanos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("escolaridadtipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("estadocivil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("estadocivilotro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("generoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sexoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ERep.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aguascalientes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Baja California"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Baja California Sur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Campeche"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chiapas"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chihuahua"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Coahuila"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Colima"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ciudad de México"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Durango"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Guanajuato"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Guerrero"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Hidalgo"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Jalisco"
                        },
                        new
                        {
                            Id = 15,
                            Name = "México"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Michoacán"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Morelos"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Nayarit"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Nuevo León"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Oaxaca"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Puebla"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Querétaro"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Quintana Roo"
                        },
                        new
                        {
                            Id = 24,
                            Name = "San Luis Potosí"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Sinaloa"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sonora"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Tabasco"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Tamaulipas"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Tlaxcala"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Veracruz"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Yucatán"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Zacatecas"
                        });
                });

            modelBuilder.Entity("ERep.Models.CSR", b =>
                {
                    b.HasOne("ERep.Models.Patient", null)
                        .WithMany("CSRs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERep.Models.PartosInfo", b =>
                {
                    b.HasOne("ERep.Models.CSR", null)
                        .WithMany("PartosInfos")
                        .HasForeignKey("CSRId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ERep.Models.Patient", b =>
                {
                    b.HasOne("ERep.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("ERep.Models.CSR", b =>
                {
                    b.Navigation("PartosInfos");
                });

            modelBuilder.Entity("ERep.Models.Patient", b =>
                {
                    b.Navigation("CSRs");
                });
#pragma warning restore 612, 618
        }
    }
}
